# Sample values
resource_group_name = "rg-tf-db-ai-demo"
location            = "uksouth"
databricks_workspace_name   = "db-workspace-demo"
databricks_sku              = "trial"
managed_resource_group_name = "db-managed-rg-demo"
storage_account_name        = "sa_databricks-ppdemo"
storage_account_sku_name    = "Standard_LRS"
databricks_user_name        = "pp-test-user@databricks.com"
databricks_display_name     = "PP-Test User"