name: Run Azure CLI Login with OpenID Connect
on: 
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    #- name: Checkout code
    #  uses: actions/checkout@v4
    #  with:
    #    sparse-checkout: .

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
          terraform_version: 1.5.7
          terraform_wrapper: false

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform changes
      run: terraform apply -auto-approve